"""initial migration

Revision ID: 119e2ea22b1e
Revises: 
Create Date: 2023-09-26 22:10:44.460220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119e2ea22b1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('register_time', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_type', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('raw_score', sa.Integer(), nullable=False),
    sa.Column('best_tutorial_action', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('client_id', name=op.f('uq_user_client_id'))
    )
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.Integer(), nullable=False),
    sa.Column('end_time', sa.Integer(), nullable=False),
    sa.Column('url_part', sa.String(length=768), nullable=False),
    sa.Column('left', sa.Integer(), nullable=False),
    sa.Column('right', sa.Integer(), nullable=False),
    sa.Column('top', sa.Integer(), nullable=False),
    sa.Column('bottom', sa.Integer(), nullable=False),
    sa.Column('label_state', sa.Integer(), nullable=False),
    sa.Column('label_state_admin', sa.Integer(), nullable=False),
    sa.Column('label_update_time', sa.Integer(), nullable=True),
    sa.Column('view_id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_video')),
    sa.UniqueConstraint('file_name', name=op.f('uq_video_file_name'))
    )
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_label_state'), ['label_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_label_state_admin'), ['label_state_admin'], unique=False)

    op.create_table('connection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('client_type', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_connection_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connection'))
    )
    op.create_table('batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_time', sa.Integer(), nullable=False),
    sa.Column('return_time', sa.Integer(), nullable=True),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('num_unlabeled', sa.Integer(), nullable=False),
    sa.Column('num_gold_standard', sa.Integer(), nullable=False),
    sa.Column('user_score', sa.Integer(), nullable=True),
    sa.Column('user_raw_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['connection.id'], name=op.f('fk_batch_connection_id_connection')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batch'))
    )
    op.create_table('tutorial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Integer(), nullable=False),
    sa.Column('query_type', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['connection.id'], name=op.f('fk_tutorial_connection_id_connection')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tutorial'))
    )
    op.create_table('view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('query_type', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['connection.id'], name=op.f('fk_view_connection_id_connection')),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], name=op.f('fk_view_video_id_video')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_view'))
    )
    op.create_table('label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], name=op.f('fk_label_batch_id_batch')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_label_user_id_user')),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], name=op.f('fk_label_video_id_video')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_label'))
    )
    with op.batch_alter_table('label', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_label_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('label', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_label_user_id'))

    op.drop_table('label')
    op.drop_table('view')
    op.drop_table('tutorial')
    op.drop_table('batch')
    op.drop_table('connection')
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_label_state_admin'))
        batch_op.drop_index(batch_op.f('ix_video_label_state'))

    op.drop_table('video')
    op.drop_table('user')
    # ### end Alembic commands ###
