"""Add the GameMistakes table

Revision ID: 3872b36d8b96
Revises: ede58da98a4e
Create Date: 2024-05-10 14:34:11.334236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3872b36d8b96'
down_revision = 'ede58da98a4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_mistakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Integer(), nullable=True),
    sa.Column('mistakes', sa.Integer(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_game_mistakes_game_id_games')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_game_mistakes_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_mistakes'))
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_games_user_id_user'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_games_user_id_user'), type_='foreignkey')
        batch_op.drop_column('user_id')

    op.drop_table('game_mistakes')
    # ### end Alembic commands ###
