"""add segmentation mask view table

Revision ID: 40410e6e9eb2
Revises: 8292a29042e9
Create Date: 2025-03-21 19:14:49.972235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40410e6e9eb2'
down_revision = '8292a29042e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segmentation_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('segmentation_id', sa.Integer(), nullable=False),
    sa.Column('query_type', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['connection.id'], name=op.f('fk_segmentation_view_connection_id_connection')),
    sa.ForeignKeyConstraint(['segmentation_id'], ['segmentation_mask.id'], name=op.f('fk_segmentation_view_segmentation_id_segmentation_mask')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_segmentation_view'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('segmentation_view')
    # ### end Alembic commands ###
