"""Add AchievementDay model and fix AchievementUser model

Revision ID: 506c234bd4b9
Revises: b0f46376fd5b
Create Date: 2024-04-03 13:41:23.400822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506c234bd4b9'
down_revision = 'b0f46376fd5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievement.id'], name=op.f('fk_achievement_day_achievement_id_achievement')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_achievement_day_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_achievement_day'))
    )
    with op.batch_alter_table('achievement_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('times_received', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievement_user', schema=None) as batch_op:
        batch_op.drop_column('times_received')

    op.drop_table('achievement_day')
    # ### end Alembic commands ###
