"""New fields in ModelScores table

Revision ID: 7be7ae7807a6
Revises: f7d8a8ba8a21
Create Date: 2024-04-13 09:40:31.783637

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = '7be7ae7807a6'
down_revision = 'f7d8a8ba8a21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    result = conn.execute(text("SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'fk_achievement_records_achievement_id_achievement'"))
    constraint_exists = result.fetchone()
    
    if constraint_exists is None:
        # ### commands auto generated by Alembic - please adjust! ###
        with op.batch_alter_table('achievement_records', schema=None) as batch_op:
            batch_op.create_foreign_key(batch_op.f('fk_achievement_records_achievement_id_achievement'), 'achievement', ['achievement_id'], ['id'])

    with op.batch_alter_table('model_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tp', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('tn', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('fp', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('fn', sa.Integer(), nullable=False))
        batch_op.drop_column('accuracy')
        batch_op.drop_column('specificity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specificity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_column('fn')
        batch_op.drop_column('fp')
        batch_op.drop_column('tn')
        batch_op.drop_column('tp')

    with op.batch_alter_table('achievement_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_achievement_records_achievement_id_achievement'), type_='foreignkey')

    # ### end Alembic commands ###
