"""add frame number for segmentation feedback

Revision ID: 8292a29042e9
Revises: b004685a9e19
Create Date: 2025-03-13 21:09:53.383399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8292a29042e9'
down_revision = 'b004685a9e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segmentation_feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frame_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segmentation_feedback', schema=None) as batch_op:
        batch_op.drop_column('frame_number')

    # ### end Alembic commands ###
