"""bug fix

Revision ID: a86460cc66b3
Revises: bc97902d95f7
Create Date: 2024-08-26 15:23:34.005422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a86460cc66b3'
down_revision = 'bc97902d95f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segmentation_batch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_unlabeled', sa.Integer(), nullable=False))
        batch_op.drop_column('num_need_feedback')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segmentation_batch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_need_feedback', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('num_unlabeled')

    # ### end Alembic commands ###
