"""Add Weekly,Monthly,Yearly Score Tables

Revision ID: acb2cc9a1ad2
Revises: 506c234bd4b9
Create Date: 2024-04-05 13:36:03.464266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acb2cc9a1ad2'
down_revision = '506c234bd4b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('raw_score', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_monthly_score_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monthly_score'))
    )
    op.create_table('weekly_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('raw_score', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_weekly_score_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weekly_score'))
    )
    op.create_table('yearly_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('raw_score', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_yearly_score_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_yearly_score'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yearly_score')
    op.drop_table('weekly_score')
    op.drop_table('monthly_score')
    # ### end Alembic commands ###
