"""Add models Achievement, AchievementUser, DailyScore as a demo for achievement system

Revision ID: b0f46376fd5b
Revises: 1d79d245c372
Create Date: 2024-04-02 21:52:20.210078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f46376fd5b'
down_revision = '1d79d245c372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_achievement'))
    )
    op.create_table('achievement_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievement.id'], name=op.f('fk_achievement_user_achievement_id_achievement')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_achievement_user_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_achievement_user'))
    )
    op.create_table('daily_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('raw_score', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_daily_score_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_score'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_score')
    op.drop_table('achievement_user')
    op.drop_table('achievement')
    # ### end Alembic commands ###
