"""Add game number to specify different games

Revision ID: d45969eaacf9
Revises: 3872b36d8b96
Create Date: 2024-06-03 10:57:23.360787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd45969eaacf9'
down_revision = '3872b36d8b96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_num', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('game_num')

    # ### end Alembic commands ###
