"""Removed the connection_id field from the Games table

Revision ID: ede58da98a4e
Revises: a2ee19dc45be
Create Date: 2024-05-10 10:19:47.041898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ede58da98a4e'
down_revision = 'a2ee19dc45be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_constraint('fk_games_connection_id_connection', type_='foreignkey')
        batch_op.drop_column('connection_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connection_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_games_connection_id_connection', 'connection', ['connection_id'], ['id'])

    # ### end Alembic commands ###
